
all:	e1 e2 e3 e4 

e1: 
	gcc -fopenmp eT1_cuadrado.c -o e1

e2:	
	gcc -fopenmp eT2_cuadrado_doble.c -o e2

e3:
	gcc -fopenmp eT3_cuadrado_doble.c -o e3

e4:  
	gcc -fopenmp eT4_cuadrado_doble_tiempos.c -o e4


clean:
	rm e1 e2 e3 e4 
